name: Al abrir Issues
on: 
  issues:
    types: [opened,closed]
jobs:
  AlAbrirOCerrar:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Caso Abierto / Cerrado ${{ github.event.issue.number }}"
